package demo.jpa.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, username).
 * @Entity annotation indicates that this class is a JPA entity.
 * @Table annotation specifies the table name in the db.
 *
 *
 */
@Entity
@Table(name = "users")
public class User {

  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's email
  @NotNull
  private String email;
  
  // The user's name
  @NotNull
  private String username;
  
  @NotNull
  private String password;

  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String email, String userName, String password) {
    this.email = email;
    this.username = userName;
    this.password = password;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getUsername() {
    return username;
  }

  public void setUsername(String value) {
    this.username = value;
  }
  
  public String getPassword(){
	  return password;
  }
  
  public void setPassword(String value){
	  this.password = value;
  }
  
  @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "User {id=" + id + ", username=" + username + ", email=" + email + "}";
	}
  
  
} 