/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mageyh' at '11/3/16 12:32 PM' with Gradle 2.2
 *
 * @author mageyh, @date 11/3/16 12:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
